cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

e_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
]

# only for debug mode. Images directory
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.ProductList.as_view(), name='product_list'),
    path('<int:id>/<slug:slug>/', views.ProductDetail.as_view(),
         name='product_detail'),
    path('search/', views.ProductSearch.as_view(), name="search_results"),
    path('product/add/', views.ProductCreate.as_view(), name='product_add'),
    path('product/update/<int:id>/<slug:slug>/',
         views.ProductUpdate.as_view(),
         name='product_update'),
    path('product/delete/<int:id>/<slug:slug>/',
         views.ProductDelete.as_view(),
         name='product_delete'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    manufacturer = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, db_index=True,
                            editable=False)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)

    class Meta:
        ordering = ('name', 'manufacturer',)
        index_together = (('id', 'slug'),)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

shop/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy

from cart.forms import CartAddProductForm

from .mixins import ProductMixin
from .models import Product


class ProductList(ListView):
    model = Product
    queryset = Product.objects.all()
    context_object_name = 'products'
    paginate_by = 8
    template_name = 'shop/product/product_list.html'


class ProductDetail(ProductMixin, DetailView, FormMixin):
    context_object_name = 'product'
    template_name = 'shop/product/product_detail.html'
    form_class = CartAddProductForm


class ProductSearch(ListView):
    model = Product
    paginate_by = 8
    template_name = 'shop/product/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Product.objects.filter(
                   Q(name__icontains=query) |
                   Q(manufacturer__icontains=query))
        else:
            return Product.objects.all()


class ProductCreate(PermissionRequiredMixin, ProductMixin, CreateView):
    fields = ['name', 'manufacturer', 'description', 'price', 'image']
    template_name = 'shop/product/product_form.html'
    permission_required = 'shop.add_product'


class ProductUpdate(PermissionRequiredMixin, ProductMixin, UpdateView):
    fields = ['name', 'manufacturer', 'description', 'price', 'image']
    template_name = 'shop/product/product_form.html'
    permission_required = 'shop.change_product'


class ProductDelete(PermissionRequiredMixin, ProductMixin, DeleteView):
    success_url = reverse_lazy('shop:product_list')
    template_name = 'shop/product/product_confirm_delete.html'
    permission_required = 'shop.delete_product'

shop/templates/shop/product/product_confirm_delete.html
{% extends "shop/base.html" %}
{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class="btn btn-danger" type="submit" value="Confirm">
</form>

{% endblock %}

shop/templates/shop/product/product_detail.html
{% extends "shop/base.html" %}
{% block content %}
{% load staticfiles %}

  <div class="row">
     <div class="col-md-6">
        <div class="product-grid4">
                <div class="product-image4">

       <img class="pic-1" src="{% if product.image %}{{ product.image.url }}
                               {% else %}{% static 'img/no-image.png' %}{% endif %}" alt="{{ product.name }}">
                </div>
        </div>
     </div>
    <div class="col-md-6">
      <div class="product-grid4">
            <div class="product-content">
                <h1 class="title">
                    {{ product.name }}
                </h1>
                <h2 class="title-secondary">
                  {{ product.manufacturer }}
                </h2>
                <div class="price">
                    {{ product.price }}
                </div>
                <p>{{ product.description }}</p>
            </div>
          {% load auth_extras %}
          {% if request.user|has_group:"sellers" %}
              <a class="sellers-panel btn btn-primary" href="{% url 'shop:product_add' %}">Add new product</a>
              <a class="sellers-panel btn btn-primary" href="{% url 'shop:product_update' product.id product.slug %}">Edit {{ product.name }}</a>
              <a class="sellers-panel btn btn-danger" href="{% url 'shop:product_delete' product.id product.slug %}">Delete {{ product.name }}</a>
          {% else %}
           <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {{ form.as_p }}
            {% csrf_token %}
             <input type="submit" value="Add to Cart">
            </form>
          {% endif %}
      </div>
     </div>
  </div>




{% endblock %}

shop/templates/shop/product/product_form.html
{% extends "shop/base.html" %}
{% block content %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Save">
</form>

{% endblock %}

shop/templates/shop/product/product_list.html
{% extends "shop/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="row">
    {% for product in products %}
     <div class="col-md-3 col-sm-6 product-cart">
            <div class="product-grid4">
                <div class="product-image4">
                    <a href="{{ product.get_absolute_url }}">
                        {% if product.image %}
                        {% load thumbnail %}
                        {% thumbnail product.image "300" as im %}
                            <img class="pic-1" src="{{ im.url }}" alt="image {{ product.name }} {{ product.manufacturer }}">
                        {% endthumbnail %}
                        {% else %}
                         <img class="pic-1" src="{% static 'img/no-image.png' %}" alt="image {{ product.name }} {{ product.manufacturer }}">
                        {% endif %}
                    </a>
                </div>
            <div class="product-content">
                <h1 class="title">
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                </h1>
                <h2 class="title-secondary">{{ product.manufacturer }}</h2>
                <div class="price">
                    {{ product.price }}
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    No products.
{% endfor %}
</div>
    {% include "shop/pagination.html" with page=page_obj %}

   <div id="contact" class="container-fluid bg-grey">
  <h2 class="text-center">Contact</h2>
  <div class="row">
    <div class="col-sm-12 text-center">
        <hr>
      <p>Contact us and we'll get back to you within 24 hours.</p>



      <p><i class="fas fa-home"></i> Warsaw, PL</p>
      <p><i class="fas fa-phone"></i> </span> +48 1515151515</p>
      <p><i class="fas fa-at"></i></i></span> myemail@some-shop.com</p>
    </div>
  </div>
   </div>
</div>
</div>
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d23299.398222681448!2d21.011030957789863!3d52.13345643503043!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1spl!2spl!4v1575975320691!5m2!1spl!2spl" width="100%" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>

{% endblock %}

shop/templates/shop/product/search_results.html
{% extends "shop/base.html" %}

{% block content %}
<p>Searched phrase: "<strong>{{ request.GET.q }}</strong>"</p>
<div class="row">
    {% for product in object_list %}
     <div class="col-md-3 col-sm-6">
            <div class="product-grid4">
                <div class="product-image4">
                    <a href="{{ product.get_absolute_url }}">
                        {% load thumbnail %}
                        {% thumbnail product.image "300" as im %}
                            <img class="pic-1" src="{% if product.image %}{{ im.url }}{% endif %}" alt="image {{ product.name }} {{ product.manufacturer }}">
                        {% endthumbnail %}
                    </a>
                </div>
            <div class="product-content">
                <h1 class="title">
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                </h1>
                <h2 class="title-secondary">{{ product.manufacturer }}</h2>
                <div class="price">
                    {{ product.price }}
                </div>
            </div>
        </div>
    </div>
 {% empty %}
    <p>No results</p>
{% endfor %}
</div>
    {% include "shop/pagination.html" with page=page_obj %}
{% endblock %}