cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

e_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
]

# only for debug mode. Images directory
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.ProductList.as_view(), name='product_list'),
    path('<int:id>/<slug:slug>/', views.ProductDetail.as_view(),
         name='product_detail'),
    path('search/', views.ProductSearch.as_view(), name="search_results"),
    path('product/add/', views.ProductCreate.as_view(), name='product_add'),
    path('product/update/<int:id>/<slug:slug>/',
         views.ProductUpdate.as_view(),
         name='product_update'),
    path('product/delete/<int:id>/<slug:slug>/',
         views.ProductDelete.as_view(),
         name='product_delete'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    manufacturer = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, db_index=True,
                            editable=False)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)

    class Meta:
        ordering = ('name', 'manufacturer',)
        index_together = (('id', 'slug'),)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])

shop/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy

from cart.forms import CartAddProductForm

from .mixins import ProductMixin
from .models import Product


class ProductList(ListView):
    model = Product
    queryset = Product.objects.all()
    context_object_name = 'products'
    paginate_by = 8
    template_name = 'shop/product/product_list.html'


class ProductDetail(ProductMixin, DetailView, FormMixin):
    context_object_name = 'product'
    template_name = 'shop/product/product_detail.html'
    form_class = CartAddProductForm


class ProductSearch(ListView):
    model = Product
    paginate_by = 8
    template_name = 'shop/product/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Product.objects.filter(
                   Q(name__icontains=query) |
                   Q(manufacturer__icontains=query))
        else:
            return Product.objects.all()


class ProductCreate(PermissionRequiredMixin, ProductMixin, CreateView):
    fields = ['name', 'manufacturer', 'description', 'price', 'image']
    template_name = 'shop/product/product_form.html'
    permission_required = 'shop.add_product'


class ProductUpdate(PermissionRequiredMixin, ProductMixin, UpdateView):
    fields = ['name', 'manufacturer', 'description', 'price', 'image']
    template_name = 'shop/product/product_form.html'
    permission_required = 'shop.change_product'


class ProductDelete(PermissionRequiredMixin, ProductMixin, DeleteView):
    success_url = reverse_lazy('shop:product_list')
    template_name = 'shop/product/product_confirm_delete.html'
    permission_required = 'shop.delete_product'

shop/templates/shop/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load auth_extras %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

     <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body >
<div class="container">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'shop:product_list' %}">
      {% if user.is_authenticated %}Logged as: {{ request.user }}
      {% else %} You're not logged in {% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:product_list' %}">Home <span class="sr-only">(current)</span></a>
      </li>
        {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
        {% else %}
         <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Register</a>
      </li>
        {% endif %}
        {% if request.user|has_group:"sellers" %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:product_add' %}"><strong>Add new product</strong></a>
        </li>
        {% endif %}
        {% if cart|length > 0 %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}">Cart</a>
        </li>
        {% endif %}
    </ul>
  </div>
        {% include "shop/searchform.html" %}
</nav>
    <div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Vines shop</h1>
    <p class="lead">vine cuttings</p>
  </div>
</div>
    <div id="content">
         <h2 class="text-center"> </h2>
        <hr>
        {% block content %}
        {% endblock %}
    </div>

</div>
</body>
</html>

shop/templates/shop/pagination.html
{% if page.paginator.num_pages > 1 %}
<div class="pagination justify-content-center">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}
{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a>
        {% endif %}
        <span class="current">
            {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
            {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}
{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
            {% endif %}
    </span>
</div>
{% endif %}

shop/templates/shop/searchform.html
        <form class="form-inline" id="searchform" action="{% url 'shop:search_results' %}" method="get" accept-charset="utf-8">
            <input class="form-control mr-sm-2" id="searchbox" name="q" type="search" placeholder="Search">
            <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
        </form>